print("y-axis")
print("^")
print("|")
print("|")
print("|")
print("|")
print("|")
print("|")
print("|")
print("|")
print("|")
print("|")
print("|___________________________________________>","x-axis ")
print("   1  2  3  4  5  6  7  8  9  10  11  12  13>")
print("0,0")