print("y-axis")
print("^")
print("|")
print("|")
print("|")
print("|")
print("|")
print("|")
print("|")
print("|")
print("|")
print("|")
print("|__1__2__3__4__5__6__7__8__9__10__11__12__13__>","x-axis ")
print("0,0")